#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : golang-github-codegangsta-cli
Version  : 71f57d300dd6a780ac1856c005c4b518cfd498ec
Release  : 1
URL      : https://github.com/codegangsta/cli/archive/71f57d300dd6a780ac1856c005c4b518cfd498ec.tar.gz
Source0  : https://github.com/codegangsta/cli/archive/71f57d300dd6a780ac1856c005c4b518cfd498ec.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
BuildRequires : go

%description
[![Coverage](http://gocover.io/_badge/github.com/codegangsta/cli?0)](http://gocover.io/github.com/codegangsta/cli)
[![Build Status](https://travis-ci.org/codegangsta/cli.svg?branch=master)](https://travis-ci.org/codegangsta/cli)
[![GoDoc](https://godoc.org/github.com/codegangsta/cli?status.svg)](https://godoc.org/github.com/codegangsta/cli)
[![codebeat](https://codebeat.co/badges/0a8f30aa-f975-404b-b878-5fab3ae1cc5f)](https://codebeat.co/projects/github-com-codegangsta-cli)

%prep
%setup -q -n cli-71f57d300dd6a780ac1856c005c4b518cfd498ec

%build

%install
gopath="/usr/lib/golang"
library_path="github.com/codegangsta/cli"
rm -rf %{buildroot}
install -d -p %{buildroot}${gopath}/src/${library_path}/
for file in $(find . -iname "*.go" -o -iname "*.h" -o -iname "*.c") ; do
     echo ${file}
     install -d -p %{buildroot}${gopath}/src/${library_path}/$(dirname $file)
     cp -pav $file %{buildroot}${gopath}/src/${library_path}/$file
done

%check
gopath="/usr/lib/golang"
export GOPATH="%{buildroot}${gopath}"
go test -v -x github.com/codegangsta/cli

%files
%defattr(-,root,root,-)
/usr/lib/golang/src/github.com/codegangsta/cli/altsrc/flag.go
/usr/lib/golang/src/github.com/codegangsta/cli/altsrc/flag_test.go
/usr/lib/golang/src/github.com/codegangsta/cli/altsrc/helpers_test.go
/usr/lib/golang/src/github.com/codegangsta/cli/altsrc/input_source_context.go
/usr/lib/golang/src/github.com/codegangsta/cli/altsrc/map_input_source.go
/usr/lib/golang/src/github.com/codegangsta/cli/altsrc/yaml_command_test.go
/usr/lib/golang/src/github.com/codegangsta/cli/altsrc/yaml_file_loader.go
/usr/lib/golang/src/github.com/codegangsta/cli/app.go
/usr/lib/golang/src/github.com/codegangsta/cli/app_test.go
/usr/lib/golang/src/github.com/codegangsta/cli/category.go
/usr/lib/golang/src/github.com/codegangsta/cli/cli.go
/usr/lib/golang/src/github.com/codegangsta/cli/command.go
/usr/lib/golang/src/github.com/codegangsta/cli/command_test.go
/usr/lib/golang/src/github.com/codegangsta/cli/context.go
/usr/lib/golang/src/github.com/codegangsta/cli/context_test.go
/usr/lib/golang/src/github.com/codegangsta/cli/flag.go
/usr/lib/golang/src/github.com/codegangsta/cli/flag_test.go
/usr/lib/golang/src/github.com/codegangsta/cli/help.go
/usr/lib/golang/src/github.com/codegangsta/cli/help_test.go
/usr/lib/golang/src/github.com/codegangsta/cli/helpers_test.go
